# Generated by Django 5.0.6 on 2025-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='banner',
            field=models.URLField(default='', max_length=1024),
        ),
    ]
