# Generated by Django 5.0.6 on 2025-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercategory',
            name='image2',
            field=models.URLField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='image3',
            field=models.URLField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='image4',
            field=models.URLField(default='', max_length=1024),
        ),
    ]
