# Generated by Django 5.0.6 on 2025-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_supercategory_image2_supercategory_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supercategory',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='supercategory',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='supercategory',
            name='image4',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='image2',
            field=models.URLField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='image3',
            field=models.URLField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='image4',
            field=models.URLField(default='', max_length=1024),
        ),
    ]
