# Generated by Django 5.0.6 on 2025-04-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_remove_supercategory_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='image2',
            new_name='banner2',
        ),
        migrations.RenameField(
            model_name='maincategory',
            old_name='image3',
            new_name='banner3',
        ),
        migrations.RenameField(
            model_name='maincategory',
            old_name='image4',
            new_name='banner4',
        ),
    ]
