# Generated by Django 5.0.6 on 2025-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_rename_image2_maincategory_banner2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='banner1',
            field=models.URLField(default='', max_length=1024),
        ),
    ]
