# Generated by Django 5.0.6 on 2025-05-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_maincategory_banner1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField(max_length=1024)),
                ('url', models.URLField(default='', max_length=1024)),
            ],
        ),
    ]
