# Generated by Django 5.2.16 on 2026-10-08 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='supercategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maincategories', to='mainApp.supercategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='supercategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supercategory_products', to='mainApp.supercategory'),
        ),
    ]
