# Generated by Django 5.2.16 on 2026-10-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_maincategory_supercategory_product_supercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='app_background',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='image',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
