# Generated by Django 5.2.16 on 2026-10-08 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_brand_image_alter_category_app_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.product'),
        ),
    ]
